name: Unity Actions

on:
  push:
    branches: []

env:
  UNITY_EMAIL: ${{ secrets.TEMP_UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.TEMP_UNITY_PASSWORD }}
  UNITY_LICENSE: ${{ secrets.TEMP_UNITY_LINUX_LICENSE }}

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on:
      labels: ["linux", "8cores"]
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - nekoyume
        targetPlatform:
          - Android
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true

      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-

      - uses: game-ci/unity-builder@v2
        with:
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: 'Editor.Builder.BuildAndroidStandalone'
          androidKeystoreName: 'virtuos-password-123456.keystore'
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEY_ALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEY_ALIAS_PASS }}
          androidTargetSdkVersion: AndroidApiLevel28
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build
