name: Unity Actions

on:
  push:
    branches: []
    tags: ["*"]

env:
  UNITY_LICENSE: ${{ secrets.ULF_2021 }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on:
      labels: ["linux", "8cores"]
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - nekoyume
        unityVersion:
          - 2021.3.5f1
        targetPlatform:
          - Android
    steps:
      - name: Set environment variables
        run: |
          targetPlatform=${{ matrix.targetPlatform }}
          if [ "$targetPlatform" == "StandaloneWindows" ]; then
            echo "DOCKER_IMAGE_TAG=${{ matrix.unityVersion }}-windows-mono-1" >> $GITHUB_ENV
          elif [ "$targetPlatform" == "macOS" ]; then
            echo "DOCKER_IMAGE_TAG=${{ matrix.unityVersion }}-mac-mono-1" >> $GITHUB_ENV
          elif [ "$targetPlatform" == "Linux" ]; then
            echo "DOCKER_IMAGE_TAG=${{ matrix.unityVersion }}-linux-il2cpp-1" >> $GITHUB_ENV
          elif [ "$targetPlatform" == "Android" ]; then
            echo "DOCKER_IMAGE_TAG=${{ matrix.unityVersion }}-android-1" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true

      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-

      - uses: game-ci/unity-builder@v2
        with:
          customImage: 'unityci/editor:${DOCKER_IMAGE_TAG}'
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
          androidKeystoreName: 'virtuos-password-123456.keystore'
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEY_ALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEY_ALIAS_PASS }}
          androidTargetSdkVersion: AndroidApiLevel28
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build
