name: Unity Actions

on:
  push:
    branches: []

env:
  UNITY_EMAIL: ${{ secrets.TEMP_UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.TEMP_UNITY_PASSWORD }}
  UNITY_LICENSE: ${{ secrets.TEMP_UNITY_LINUX_LICENSE }}

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on:
      labels: ["linux", "8cores"]
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - nekoyume
        targetPlatform:
          - Android
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf true
          git config --global core.eol crlf

      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true

      - uses: game-ci/unity-builder@v2
        with:
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: 'Editor.Builder.BuildAndroidStandalone'
          androidTargetSdkVersion: AndroidApiLevel28

      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build
