name: Unity Actions

on:
  push:
    branches: []
    tags: ["*"]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  PROJECT_PATH: necoyume

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on:
      labels: ["linux", "8cores"]
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true

      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      # https://github.com/game-ci/unity-builder/releases/
      - uses: game-ci/unity-builder@v2
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build
